# Generated by Django 3.1.4 on 2020-12-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTable',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=50)),
                ('TeamMembers', models.CharField(max_length=500)),
                ('Coach', models.CharField(max_length=50)),
                ('Manager', models.CharField(max_length=50)),
            ],
        ),
    ]
