# Generated by Django 3.1.4 on 2020-12-10 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('team_a_points', models.IntegerField(null=True)),
                ('team_b_points', models.IntegerField(null=True)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teama', to='polls.registrationtable')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamb', to='polls.registrationtable')),
            ],
        ),
    ]
